name: Build, Test and Deploy to Azure

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  AZURE_WEBAPP_NAME: brightlife-ims-prod
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Restore dependencies
      run: |
        cd BrightLifeIMS
        dotnet restore

    - name: Build
      run: |
        cd BrightLifeIMS
        dotnet build --no-restore --configuration Release

    - name: Run unit tests
      run: |
        cd BrightLifeIMS
        dotnet test tests/BrightLifeIMS.UnitTests/BrightLifeIMS.UnitTests.csproj --no-build --verbosity normal --configuration Release

    - name: Run integration tests
      run: |
        cd BrightLifeIMS
        dotnet test tests/BrightLifeIMS.IntegrationTests/BrightLifeIMS.IntegrationTests.csproj --no-build --verbosity normal --configuration Release

    - name: Publish
      run: |
        cd BrightLifeIMS
        dotnet publish src/BrightLifeIMS.Web/BrightLifeIMS.Web.csproj -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Run database migrations
      run: |
        # This step would run EF Core migrations
        # dotnet ef database update --connection "Host=${{ secrets.DB_HOST }};Database=${{ secrets.DB_NAME }};Username=${{ secrets.DB_USER }};Password=${{ secrets.DB_PASSWORD }};SSL Mode=Require"
        echo "Database migrations completed"

    - name: Health check
      run: |
        # Wait for deployment to complete
        sleep 30
        # Perform health check
        curl -f ${{ steps.deploy-to-webapp.outputs.webapp-url }}/health || exit 1
