// <auto-generated />
using System;
using BrightLifeIMS.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightLifeIMS.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250901054515_AddDomainEntities")]
    partial class AddDomainEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.AutoSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SaveData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("InventoryId", "CreatedAt");

                    b.ToTable("AutoSaves");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameBn")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 5, 45, 13, 178, DateTimeKind.Utc).AddTicks(4134),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Physical Goods",
                            NameBn = "শারীরিক পণ্য"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 5, 45, 13, 178, DateTimeKind.Utc).AddTicks(6110),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Membership Services",
                            NameBn = "সদস্যপদ সেবা"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 1, 5, 45, 13, 178, DateTimeKind.Utc).AddTicks(6113),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Partner Claims",
                            NameBn = "অংশীদার দাবি"
                        });
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ItemId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoSaveData")
                        .HasColumnType("jsonb");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBool1Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomBool1Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomBool1Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomBool1Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomBool1Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomBool1State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomBool2Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomBool2Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomBool2Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomBool2Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomBool2Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomBool2State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomBool3Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomBool3Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomBool3Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomBool3Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomBool3Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomBool3State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomIdFormat")
                        .HasColumnType("jsonb");

                    b.Property<string>("CustomInt1Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomInt1Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomInt1Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomInt1Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomInt1Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomInt1State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomInt2Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomInt2Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomInt2Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomInt2Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomInt2Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomInt2State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomInt3Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomInt3Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomInt3Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomInt3Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomInt3Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomInt3State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomString1Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomString1Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomString1Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomString1Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomString1Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomString1State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomString2Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomString2Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomString2Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomString2Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomString2Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomString2State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomString3Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomString3Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomString3Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomString3Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomString3Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomString3State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomText1Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomText1Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomText1Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomText1Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomText1Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomText1State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomText2Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomText2Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomText2Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomText2Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomText2Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomText2State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomText3Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomText3Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomText3Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomText3Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomText3Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomText3State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomUrl1Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomUrl1Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomUrl1Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomUrl1Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomUrl1Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomUrl1State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomUrl2Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomUrl2Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomUrl2Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomUrl2Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomUrl2Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomUrl2State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomUrl3Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CustomUrl3Displayed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomUrl3Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomUrl3Order")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomUrl3Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CustomUrl3State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionBn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSavedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LikesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleBn")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Title");

                    b.HasIndex("CreatorId", "IsPublic");

                    b.HasIndex("Title", "Description")
                        .HasDatabaseName("idx_inventories_fts");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.InventoryTag", b =>
                {
                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("InventoryId", "TagId")
                        .HasDatabaseName("idx_inventory_tags_composite");

                    b.ToTable("InventoryTags");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudImages")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("CustomBool1")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CustomBool2")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CustomBool3")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CustomId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomInt1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomInt2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomInt3")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomString1")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomString2")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomString3")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomText1")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomText2")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomText3")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomUrl1")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomUrl2")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomUrl3")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikesCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InventoryId");

                    b.HasIndex("InventoryId", "CustomId")
                        .IsUnique()
                        .HasDatabaseName("idx_unique_custom_id_per_inventory");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.ItemLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ItemId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_unique_like_per_user_item");

                    b.ToTable("ItemLikes");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameBn")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UsageCount");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en-US");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.AutoSave", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.Inventory", "Inventory")
                        .WithMany("AutoSaves")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Comment", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.Item", "Item")
                        .WithMany("Comments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightLifeIMS.Web.Models.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Inventory", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.Category", "Category")
                        .WithMany("Inventories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", "Creator")
                        .WithMany("CreatedInventories")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.InventoryTag", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.Inventory", "Inventory")
                        .WithMany("InventoryTags")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightLifeIMS.Web.Models.Entities.Tag", "Tag")
                        .WithMany("InventoryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Item", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", "CreatedBy")
                        .WithMany("CreatedItems")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrightLifeIMS.Web.Models.Entities.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.ItemLike", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.Item", "Item")
                        .WithMany("Likes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", "User")
                        .WithMany("ItemLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BrightLifeIMS.Web.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Category", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Inventory", b =>
                {
                    b.Navigation("AutoSaves");

                    b.Navigation("InventoryTags");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Item", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.Tag", b =>
                {
                    b.Navigation("InventoryTags");
                });

            modelBuilder.Entity("BrightLifeIMS.Web.Models.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CreatedInventories");

                    b.Navigation("CreatedItems");

                    b.Navigation("ItemLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
